### ISSUE TITLE
No change when modifying meta and links

### ISSUE THREAD

**Issue by zarevskaya** [nandolawson/LinkLoom#4]
Hello, I discovered your application!

When I make changes in links or meta, nothing happens.
I tried by cloning the project or creating the files by hand.

Logs are linked.

Have a nice day!
[_linkloom_logs.txt](https://github.com/user-attachments/files/17616666/_linkloom_logs.txt)

**Comment by nandolawson** [comment]
Hey

You're trying to host via Docker, right? I've changed a few things in the config as a test and can see the changes straight away. Would you mind sending me your meta.json?

**Comment by zarevskaya** [comment]
Yes, with Docker.
`{
    "favicon": "https://github.com/fluidicon.png",
    "language": "english",
    "name": "zarev",
    "picture": "https://github.com/fluidicon.png",
    "title": "belginux"
}
`
![Screenshot_20241104_114407](https://github.com/user-attachments/assets/b089e220-8a68-4e1e-ac61-ecbc3aff1bad)

**Comment by zarevskaya** [comment]
OMG, it was the cache... Sorry -_'

**Comment by nandolawson** [comment]
I was just about to make that assumption myself. No problem. :D

**Comment by zarevskaya** [comment]
Thank you for your kindness ;)
