### ISSUE TITLE
Change wallpaper

### ISSUE THREAD

**Issue by zarevskaya** [nandolawson/LinkLoom#5]
Hey!

Do you plan on being able to add your own wallpaper?

**Comment by nandolawson** [comment]
Do you mean the ability to insert normal images as background images? If so, that would be very easy to do.

**Comment by zarevskaya** [comment]
Yes, with particles it could be interesting. :+1:

**Comment by nandolawson** [comment]
I'll look into it after I fixed [this bug](https://github.com/nandolawson/LinkLoom/issues/2).

**Comment by zarevskaya** [comment]
Take your time, it's already nice to listen to requests. It's up to us to be patient. Thanks @nandolawson

**Comment by nandolawson** [comment]
The feature is finished. There is still a small cosmetic error when scrolling, but this shouldn't be too annoying. This will of course be fixed as well.

**Comment by zarevskaya** [comment]
I'll try! THANKS! 

At the moment I'm unlucky I have a blank page.

Failed to load for <script> element whose source is “http://192.168.1.152:5500/scripts/links.js
