### ISSUE TITLE
Blank page since the last update

### ISSUE THREAD

**Issue by zarevskaya** [nandolawson/LinkLoom#7]
Hello ;)

Since the last update I have a blank page, when I push on F12, I have this message:

Failed to load for <script> element whose source is “http://192.168.1.152:5500/scripts/links.js

**Comment by nandolawson** [comment]
I think this is an issue that comes with the updated Dockerfile. Give me a sec.

**Comment by zarevskaya** [comment]
Of course, thanks!

**Comment by nandolawson** [comment]
Fixed. I'll remove the broken images from GHCR and Docker Hub. Thanks for the info!

**Comment by zarevskaya** [comment]
It's strange, I cleared the cache, I started everything again from scratch. The changes I make have no effect. Nor on the links, the metas. I can't display the background either.

Can you confirm?

**Comment by zarevskaya** [comment]
The cookie “_gh_sess” has been rejected because it is in a cross-site context and its “SameSite” value is “Lax” or “Strict”. fluidicon.png
The “_octo” cookie has been rejected because it is in a cross-site context and its “SameSite” value is “Lax” or “Strict”. fluidicon.png
The “logged_in” cookie has been rejected because it is in a cross-site context and its “SameSite” value is “Lax” or “Strict”. fluidicon.png
The cookie “_gh_sess” has been rejected because it is in a cross-site context and its “SameSite” value is “Lax” or “Strict”. fluidicon.png
The “_octo” cookie has been rejected because it is in a cross-site context and its “SameSite” value is “Lax” or “Strict”. fluidicon.png
The “logged_in” cookie has been rejected because it is in a cross-site context and its “SameSite” value is “Lax” or “Strict”.

**Comment by nandolawson** [comment]
Nope. Everything works as it should for me. Maybe you started the container twice?

**Comment by zarevskaya** [comment]
Oh, weird. I have the same issue on all my VMs, across different browsers.

**Comment by nandolawson** [comment]
That is really weird. I would still assume that there is a problem somewhere in your server configuration. Some values ​​are set automatically by LinkLoom if they are missing or incorrect. Links, for example, are not included. What happens if you don't have a links.json at all?

**Comment by zarevskaya** [comment]
I just installed Brave and got the same error. New CT in Proxmox, same problem. I am cursed. I'm going to test on a friend's server.

**Comment by nandolawson** [comment]
If the same behavior occurs there, I would be grateful if you would open a new issue.

**Comment by zarevskaya** [comment]
Do you have an email address because I rented a vps and I have the same problem. I can give you access?
