### ISSUE TITLE
No change after editing

### ISSUE THREAD

**Issue by zarevskaya** [nandolawson/LinkLoom#8]
Hello, again!

I just rented a small vps to make sure it's not an error on my network.

It's strange, I cleared the cache, I started everything again from scratch. The changes I make in meta/links have no effect. Nor on the links, the metas. I can't display the background either.

Do you want me to provide access to the VPS?

**Comment by nandolawson** [comment]
If you want, I can take a look tomorrow. Maybe I can even learn something myself.

Generally, I would still like to say that you shouldn't give anyone access to your servers that you don't completely trust. In the worst case scenario, this puts your data and services at great risk. If you still want me to try to find the problem, let me know. I'll then send you my email address/SSH key. As long as there is no sensitive data on the VPS, it should not pose a security risk to you.

**Comment by zarevskaya** [comment]
Thanks! This is not my home server, but a simple vps that I rented while the problem was being resolved. There is only your application. This was to eliminate the internal problem. Rest assured. The vps contains absolutely nothing else and will be destroyed afterwards.

**Comment by nandolawson** [comment]
All right, I'll get in touch tomorrow. If you have Discord or Reddit, for example, you can contact me there too. Same username as here.

**Comment by zarevskaya** [comment]
Information sent by Reddit. :+1:

**Comment by nandolawson** [comment]
In case anyone has the same problem, the problem was trying to clone the repository, start the container via Docker Compose, and then change the configs in the repository. However, this didn't work via Compose because a volume was used in which the configs were located. I updated the Docker Compose file to use the "config" folder, which is in the same folder as the Compose.
